name: getx_admob
description: "Implement AdMob using GetX in Flutter. Easy to use Admob in your Flutter when you use GetX. Only for Android and iOS."
version: 0.0.2
homepage: https://github.com/LunaGao/getx_admob

environment:
  sdk: ^3.10.9
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.3
  google_mobile_ads: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
